include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - always_use_package_imports
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - sort_pub_dependencies
    - super_goes_last
    - use_enums
    - use_is_even_rather_than_modulo
